### PR TITLE
Add simple Makefile

### PR DESCRIPTION
**Pull request by raatmarien**
I wanted to try this project, but I didn't want to install Eclipse. Maybe this will help others build it easier.

### CODE REVIEW

**Comment by egordorichev** [comment]
:+1: +1

**Comment by egordorichev** [comment]
Don't forget to add info about makefile into README.md.

**Comment by hydren** [comment]
Sorry for the delay! How do I test the makefile?

**Comment by raatmarien** [comment]
Assuming you are on Linux:
- install make
- place the makefile at terrarium/
- open a shell,  go to terrarium/ and execute:
  make
- run it by executing:
  ./terrarium

**Comment by hydren** [comment]
Thank you for the help! I'm in my work right now, so tonight I will try it and accept the pull.

**Comment by hydren** [comment]
I assume I'll have to update the makefile when adding or removing source files, right?

**Comment by hydren** [comment]
By the way, I accepted the pull request. Thank you for your help!

**Comment by raatmarien** [comment]
Yes,  you'll have to add any new object files to OBJ. 

No problem :)

**Pull request merged**
